apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "device-api.fullname" . }}
  namespace: {{ include "device-api.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: device-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ota-controller
      ports:
        - port: 7070
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53

