apiVersion: v1
kind: Service
metadata:
  name: {{ include "device-api.fullname" . }}
  namespace: {{ include "device-api.namespace" . }}
  labels:
    app.kubernetes.io/name: device-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: device-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

