apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-ingestor.fullname" . }}
  namespace: {{ include "telemetry-ingestor.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
{{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: telemetry-ingestor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telemetry-ingestor
    spec:
      serviceAccountName: {{ default (include "telemetry-ingestor.fullname" .) .Values.serviceAccount.name }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: telemetry-ingestor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "telemetry-ingestor.fullname" . }}
            - secretRef:
                name: {{ .Values.externalSecret.targetName }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

