{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "telemetry-ingestor.fullname" . }}
  namespace: {{ include "telemetry-ingestor.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "telemetry-ingestor.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpuAverageUtilization }}
    - type: Pods
      pods:
        metric:
          name: {{ .Values.hpa.customMetric.name }}
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.customMetric.targetAverageValue }}
{{- end }}

