{{- if (default false (dig "hpa" "enabled" false .Values)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mqtt-broker.fullname" . }}
  namespace: {{ include "mqtt-broker.namespace" . }}
spec: {}
{{- end }}
