apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-broker.fullname" . }}
  namespace: {{ include "mqtt-broker.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: mqtt-broker
  ports:
    - name: mqtt
      port: {{ .Values.service.ports.mqtt }}
      targetPort: mqtt
    - name: mqtt-tls
      port: {{ .Values.service.ports.tls }}
      targetPort: mqtt-tls

