apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ota-controller.fullname" . }}
  namespace: {{ include "ota-controller.namespace" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ota-controller

